### ISSUE TITLE
Non-overlapping cameras calibration

### ISSUE THREAD

**Issue by Lashhev** [rameau-fr/MC-Calib#22]
### System information (version)

* Operating System / Platform = ubuntu 18.04
* OpenCV = 4.2.0
* Ceres = 2.0.0
* Boost = 1.71.0
* C++ = 14
* Compiler = g++ 8.4.0

### Vision system

* Number of cameras = 3
* Types of cameras = perspective
* Multicamera configurations = non-overlapping
* Configuration file = [GLAM.zip](https://github.com/rameau-fr/MC-Calib/files/9112379/GLAM.zip)
### Describe the issue / bug

Hello! Is it proper configuration when I use only 2 board to calibrate 3 non-overlapping cameras? Program throws this exception:
"terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/calib3d/src/calibration_handeye.cpp:705: error: (-215:Assertion failed) R_gripper2base_.size() >= 3 in function 'calibrateHandEye'"

**Comment by rameau-fr** [comment]
Thank you very much for your feedback.

I have not yet faced this issue but it seems that MC-Calib does not find enough views for the hand-calibration strategy. 

When I see your configuration file, I noticed a few things:
- 1.  the boards_index parameter could be left empty [] since you use only two boards (I do not think this one is causing any issue)
- 2. You set fix_intrinsic: 1 but you do not provide any parameters since cam_params_path: "None" (This can be a substancial problem, I do not remember if we deal with this exception so I would recommend to set to "0" or to provide a valid initial intrinsic calibration of your cameras).
- You can try to set "he_approach: 1" in the configuration file, it will employ a different hand-eye calibration strategy (but I do not think it is gonna help in your case).

A few additional questions:
- How many synchronized images are you using per cameras?
- What is the image resolution of each cameras?
- Would it be possible to share your data (or a subset of it) such that we can debug this issue more effectively? 

Thanks a lot for your message, it truly help us improving MC-Calib!

**Comment by rameau-fr** [comment]
Have you managed to resolve your problem? 
please let us know if you are facing any further issues, you can also send us your pictures if you want us to check.
